### ISSUE TITLE
Changelog too large for 1080p screens

### ISSUE THREAD

**Issue by clarjon1** [raiguard/ModernGadgets#104]
The changelog for the latest update is too large to be fully read on a 1080p screen.

I'd recommend setting a maximum height to the widget if possible, and adding a scroll bar, so that it's visible, or at least a partial list of changes with a link to the full changelog.

I'm glad I had a 2k display attached as well so I could actually access the button to update, however those without a 2k display won't be able to access the button.
![changelogtoobig](https://user-images.githubusercontent.com/627845/46700920-221f5800-cbec-11e8-8669-917cb7ed362f.jpg)

**Comment by raiguard** [comment]
Oops! Someone else already reported this, but I got sidetracked and forgot to update it. Future changelogs will never be as large as this one (I feature-creeped on this update because the new HWiNFO SMV was taking a while to be made by stangowner) so this should never be a problem again. In the meantime, I'll shorten the changelog so people can click the button...

**Comment by raiguard** [comment]
Should be fixed now. Thanks for the report.
