### ISSUE TITLE
hide cpu cores details

### ISSUE THREAD

**Issue by dosoft** [raiguard/ModernGadgets#123]
is it possible to hide cpu cores details? frankly speaking, I just need a total values (usage, temp) and don't care about every of 12 cores :)

**Comment by raiguard** [comment]
Sorry I've been busy with life stuff so I haven't been looking at this project for a while.

There is no official feature for this (though I have considered adding one, I am trying to prioritize what I want to add since I have a limited time frame to do it in), but you can achieve the same effect by right-clicking on CPU Meter and clicking `Edit Skin`. Scroll down to the `[MeasureCpuLogicalCores]` section and replace `Formula=%NUMBER_OF_PROCESSORS%` with `Formula=0`. Save the file, middle-click CPU Meter (or right-click and select `Refresh Skin`) and the cores will disappear.

You'll have to go into the CPU Meter settings skin and check the `Average CPU Usage Graph` option, as well as change the CPU Temperature display to `Standard`.

Let me know if you have any other questions!

![2018-12-16 13_49_55-d__settings_caleb_rainmeter_skins_moderngadgets_settings_sidebars_control_1_sb1c](https://user-images.githubusercontent.com/3515394/50058721-81906b80-0139-11e9-92ab-6d2ee45c8d5e.png)

**Comment by raiguard** [comment]
Gonna close this since I'm pretty sure it's resolved now.

**Comment by thamatthatter** [comment]
Hey Raiguard,

While this solution does work it is not ideal especially if you do not want to use the graph. It would be cool if we could just have a single line that functions similarly to the RAM line. Seeing an average temperature as well as the usage for the entire CPU would be perfect. 

Loving it otherwise!

**Comment by raiguard** [comment]
Ironically, I just added this feature officially. Go into your global settings skin and click "opt-in to development testing". You should be prompted to download and install an update. Once you install this update, go into CPU Meter Settings and click "average CPU usage mode."

**Comment by thamatthatter** [comment]
This is much better however it seems to only display the temperature of 0 celsius no matter what I have CPU temperature set to in the CPU meter settings. When I disable Average CPU Usage Mode, my temps, all display per core correctly. My only other nitpick is that instead of saying "Usage:" it should say "CPU:" similar to "RAM:" above it. This is by far my favorite rainmeter skin though. Thank you for all your efforts!
![Annotation 2019-04-07 155848](https://user-images.githubusercontent.com/49376420/55691035-0d7b0d00-594e-11e9-99f1-41a23f82441a.jpg)
