### ISSUE TITLE
CPU usage, page files

### ISSUE THREAD

**Issue by Ilrandir** [raiguard/ModernGadgets#131]
Show a separate string for each page file (if page file is placed on two or more drives) or add a checkbox to show page files in a separate strings. Its important when you have ssd and hdd drives with page files on each, to understand perfomance issues.

Top process - Show cpu usage near process, not only process name (like "Rainmeter 20%").

Add a field in setting to show how many Top processes to show.

**Comment by raiguard** [comment]
I'll look into it, but there are a few problems:

1. I don't know if there's a way to monitor the different page files through PerfMon
2. Having a dynamic number of pagefiles would not work well with Rainmeter, since with Rainmeter, you cannot dynamically create or destroy objects.

As for the top process requests, those features already exist in the "Process Meter" gadget. You can display up to ten processes ordered by CPU Usage, and it also displays RAM usage as well.

![2019-02-04 10_12_58](https://user-images.githubusercontent.com/3515394/52224547-7fa77680-2865-11e9-9bf1-25a3f7d1f04c.png)

**Comment by raiguard** [comment]
After considering the page file features, I have determined that I am not going to implement this. I still don't know how to do it, for one, and like I said, having a dynamic number of displays doesn't work well at all with Rainmeter. Sorry! :(
