### ISSUE TITLE
Error in Update available

### ISSUE THREAD

**Issue by DrYSG** [raiguard/ModernGadgets#134]
I am running 1.4.1 and I get popups for V1.5.0-beta, but when I try to press download, I get ERROR>

is there a way to start over from scratch with the beta? (I am a bit new to rainmeter, but I have the latest beta running).

**Comment by raiguard** [comment]
Hmm, that happens when it can't download the file for some reason. If you want to start over with the beta, you'll have to completely delete the ModernGadgets skins folder, as well as the ModernGadgets entry in the @Backup folder (to prevent the settings from being imported). You can download the beta [here](https://github.com/raiguard/ModernGadgets/releases/download/v1.5.0-beta.8/ModernGadgets_1.5.0-beta.8.rmskin) and install it as normal.

**Comment by DrYSG** [comment]
Ok. Do you mind giving me a pointer to:

1. Where the modern gadgets folder is? (I only see a illustro at Rainmeter/Defaults/Skinds
2. Where the @backup folder is.

**Comment by raiguard** [comment]
1. Go into the gadget manager, and click the `MG Skins Folder` button. Go back one folder and delete the ModernGadgets folder. Then go into `@Backup` and delete ModernGadgets from there as well.

**Comment by DrYSG** [comment]
Simple pimple. Thanks
