### ISSUE TITLE
Audio Meter: Show Media & controls dynamically

### ISSUE THREAD

**Issue by Shrekmachine** [raiguard/ModernGadgets#136]
Feature request to show Media & controls only when music is playing

**Comment by raiguard** [comment]
I never thought about doing this... and it's not even going to be that difficult! It'll be in for the next beta. :)

**Comment by Shrekmachine** [comment]
just make sure that the panel is extending to the top instead down :D

**Comment by raiguard** [comment]
You mean move the top of the gadget up, rather than moving the bottom down?

This is actually very (VERY) difficult, as Rainmeter defines skin positions from the top-left of a skin. So for me to make the top go up, I would have to finagle with the skin's actual position. Sorry, but it'll move the visualizer down when it appears. :(

**Comment by Shrekmachine** [comment]
It doesn't hurt to ask  :innocent:

**Comment by raiguard** [comment]
This is now implemented in v1.5.0-beta.10, which will be releasing in a few hours.

**Comment by raiguard** [comment]
v1.5.0-beta.10 is released!
