### ISSUE TITLE
Everytime i update to the next version, my meter settings all get reset.

### ISSUE THREAD

**Issue by Faunsce** [raiguard/ModernGadgets#168]

**Comment by raiguard** [comment]
The settings, as in colors and what is shown on each gadget, or settings as in the positions of each gadget on your screen and which ones are loaded?

**Comment by Faunsce** [comment]
For example, Ill lose about half of my gadets on screen at random. I also tend to lose the srttings on gadgets such us disk meter, and the audio meter as well at the gpu meter. So a combination of both.

**Comment by raiguard** [comment]
Well the gadgets repositioning themselves is because you're not unchecking the "apply included layout" checkbox at the bottom of the installer. If you uncheck that, the gadgets will stay where they are.

As for the settings themselves, that's odd. Luckily there will be only one more patch for the next two years (hopefully). So you'll only have to deal with it one more time.

**Comment by SilverAzide** [comment]
I tested this and the gadgets did not move after upgrading, so this does seem due to the default layout being applied (i.e., leaving the box checked).  I *did* lose a few settings, but retained a lot of others.  For example, with the network gadget, the adapters reverted to the default (blank) settings, but both the weather and HWiNFO settings all were migrated perfectly.  (Still can't figure out how you did that!!)  :-)

**Comment by raiguard** [comment]
Yeah, the adapters going blank is the one thing I am aware of. That's due to a bug in Rainmeter that I reported, and they said they might fix it, but they haven't yet.

As for how I carry over the settings, take a look at the "Variables files" box when packaging an RMSKIN.

**Comment by Faunsce** [comment]
Oh ok. Thanks for letting me know, ive never noticed that box so maybe it being auto-checked isnt the best.

**Comment by raiguard** [comment]
The box being auto-checked is standard behavior for all Rainmeter skin suites that have a default layout included. There's nothing I can do about that.

**Comment by Faunsce** [comment]
Understood.
