### ISSUE TITLE
Display Issue SMV

### ISSUE THREAD

**Issue by Fishheadman** [raiguard/ModernGadgets#173]
I cannot view the entire window for SMV cannot see the update button on the right.

OS: Win 7 Pro 64 Ver. 6.1 (Build 7601 SP1)
Resolution:  1980x1080
![SMV bug](https://user-images.githubusercontent.com/55498040/65156585-5951d800-d9fd-11e9-99f3-3de9d49149ba.png)

**Comment by SilverAzide** [comment]
This problem is with a third-party component, supplied by the author of the HWiNFO plugin.  As a result, this cannot be fixed except by the plugin author.  However, you can work around this issue.  I assume you have your display scaling at some value greater than 100%?  If so, navigate to the folder C:\Users\\_username_\Documents\Rainmeter\Skins\ModernGadgets\@Resources\Addons\HWiNFO.  In this folder, right-click the HWiNFOSharedMemoryViewer.exe executable and select Properties.  From the Properties dialog, check the option "Disable display scaling on high DPI systems".  (This setting appears differently in Windows 10.)  Let us know if this works around the issue.

**Comment by SilverAzide** [comment]
Issue reported to HWiNFO plugin author.

**Comment by Fishheadman** [comment]
Hello,

Your fix didn't seem to work but it made me check my display scaling and it was set at 125%. I changed it to 100% and logged out to refresh and was able to fix the window size.  Problem solved, I appreciate the help!



________________________________

**Comment by SilverAzide** [comment]
OK, great!  I posted this issue on the plug-in author's forum thread, so we'll just have to wait for him to issue a fix.
