### ISSUE TITLE
Highest clock?

### ISSUE THREAD

**Issue by grappas** [raiguard/ModernGadgets#182]
Would It be a problem if you make CPU Monitor show highest clock of all cores instead of only core 0?

**Comment by raiguard** [comment]
I am planning to eventually rewrite CPU Meter (_again_), and when I do I'll add support for this.

**Comment by grappas** [comment]
👍

**Comment by raiguard** [comment]
Upon further investigation, it actually appears that the sensor that I told people to configure, the `Ring/LLC clock` is not an accurate reflection of the CPU's clock speed at all. I'm making this a higher priority and it will be done for v1.7.0.

**Comment by ericmassara** [comment]
This would be useful for Ryzen CPUs because often, unless conditions are ideal, many of them don't usually hit their advertised max boost clocks, so it's interesting/useful to monitor the current clock speed. HWInfo shows this info as physical core speeds, so it would be desirable to only show the physical cores (4, 8, 12, 16, etc) and not the virtual cores.

Current clock speeds what I'm interested in displaying in ModernGadgets:
![image](https://user-images.githubusercontent.com/59150098/79897745-2713b900-83d8-11ea-9d93-7caed7590ae3.png)

**Comment by raiguard** [comment]
(Finally) implemented for the next version! 🎉

**Comment by grappas** [comment]
> Only took a year...

xD
