### ISSUE TITLE
Calendar - personal

### ISSUE THREAD

**Issue by GhostKhoi** [raiguard/ModernGadgets#183]
Good day
I'd like to import my personal calendar into my calendar skin on ModernGadgets 1.6.2. Please advice

**Comment by raiguard** [comment]
The calendar skin isn't very capable. It was very rushed, and is based on someone else's work that I just adapted to my style. In order to add events to it you need to right-click on the skin and click the top button:

![image](https://user-images.githubusercontent.com/3515394/71769149-78a44080-2eda-11ea-85b9-78d8d499acc9.png)

Then open the `CalendarEvents.xml` file in a text editor (notepad will do fine). You'll have to enter your calendar events in there manually.

In the far future I might make this a bit easier, but for now, that's the way it is. Sorry, and thanks for using ModernGadgets!
