### ISSUE TITLE
monitor more than 3 GPU's 

### ISSUE THREAD

**Issue by SimonBL** [raiguard/ModernGadgets#246]
Hi could you add the possibility to monitor more than 3 GPU's at once. Thanks

**Comment by raiguard** [comment]
May I ask your usecase? I do not plan on adding any more GPU Meter variants to stock ModernGadgets, but you could fairly easily copy/paste the skin files to create as many as you wish.

**Comment by Shrekmachine** [comment]
Mining?

**Comment by SimonBL** [comment]
yes, mining.
I tried copying the whole Modern Gadgets folder then load GPUmeter from there but the settings file affects both versions. Same if I copy the subfolder GPUmeter only.

**Comment by SimonBL** [comment]
I assume I need to edit the settings files but I'm not familiar enough with rainmeter to achieve this. If anyone has pointers to help me do this it would be appreciated.

**Comment by raiguard** [comment]
Turns out there was a bug and all of the GPU Meter variants would use the same settings. I've fixed that for the next version.

To make more GPU Meters, you need to copy the `GPU3` folder and paste it, then name that `GPU4`. Edit `GPU4/GpuMeter.ini` and change `GpuSettings1.inc` to `GpuSettings4.inc`, then change `gpuIndex=3` to `gpuIndex=4`. Then navigate to `@Resources/Settings` and copy `GpuSettings3.inc` into `GpuSettings4.inc`. Finally, open `GpuSettings.inc` and scroll to the bottom, copy the `HWiNFO-Config-GPU-3]` section, paste it below, and change all of the `3`s to `4`.

Rinse and repeat as many times as you need. However, please note that you will need to do all of this again any time you update the suite.

**Comment by raiguard** [comment]
Closing. If you have any other questions, please reach out on the discussions page!
