### ISSUE TITLE
max tomperature+fan speed for GPU and CPU 

### ISSUE THREAD

**Issue by vitalisse** [raiguard/ModernGadgets#42]
can you please tell me how to add max fan speed and max temperature for CPU and the same for GPU
THANK YOU

**Comment by vitalisse** [comment]
no answer?

**Comment by iamanai** [comment]
What do you mean? Displaying them? Just retrieving the information? You're not being clear.

**Comment by vitalisse** [comment]
there is no thing like "max cpu temp" and "max gpu temp" and "max fans" in your great-full work
even i keep locking in  settings for every one of tjem...i mean cpu and gpu

**Comment by vitalisse** [comment]
of course i want to display them.

**Comment by iamanai** [comment]
HWiNFO does not have accurate readings for those values. However, if you would like to implement it anyway, you'll need to create a meter to display the value, tie it to a HWiNFO measure, and get that measure to gather the correct information from HWiNFO itself. In other words, you need to learn how to program Rainmeter skins.

I cannot help you very much because I have very limited time (we're moving house at the moment), but I will try to help as much as possible. Sorry about that.

**Comment by raiguard** [comment]
Closing this because I'm not going to implement it. If you would like to implement it yourself, feel free, but it's not on my agenda.
